-- === Schema ===

begin
    execute immediate 'drop user schema3 cascade';
    execute immediate 'drop user schema4 cascade';
exception when others then
    IF SQLCODE != -1918 THEN
        RAISE;
    END IF;
end;
/

CREATE USER schema3 IDENTIFIED BY schema1_password_tgt;
GRANT CONNECT, RESOURCE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TABLE TO schema3;

CREATE USER schema4 IDENTIFIED BY schema2_password_tgt;
GRANT CONNECT, RESOURCE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TABLE TO schema4;

-- === Tables (12) ===
CREATE TABLE schema3.emp (id NUMBER PRIMARY KEY, name VARCHAR2(50)); -- Different column
CREATE TABLE schema3.dept (dept_id NUMBER PRIMARY KEY, budget NUMBER(10, 2) DEFAULT 0); -- Different column
CREATE TABLE schema3.projects (project_id NUMBER PRIMARY KEY, project_name VARCHAR2(50)); -- Different column size, no unique
CREATE TABLE schema3.managers (manager_id NUMBER PRIMARY KEY, email VARCHAR2(100) NOT NULL); -- New table
CREATE TABLE schema3.offices (office_id NUMBER PRIMARY KEY, building_code VARCHAR2(10)); -- New table
CREATE TABLE schema4.salary (salary_id NUMBER PRIMARY KEY, amount NUMBER); -- Different column
CREATE TABLE schema4.bonus (bonus_id NUMBER PRIMARY KEY, bonus_date DATE); -- Added column
CREATE TABLE schema4.products (product_code VARCHAR2(10) PRIMARY KEY, description VARCHAR2(200)); -- New table
CREATE TABLE schema4.suppliers (supplier_id NUMBER PRIMARY KEY, phone VARCHAR2(20)); -- New table
CREATE TABLE schema4.order_items (order_item_id NUMBER PRIMARY KEY, product_code VARCHAR2(10) REFERENCES schema4.products(product_code)); -- New table
CREATE TABLE schema4.audit_log (log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, action VARCHAR2(100)); -- New table
CREATE TABLE schema3.employees_backup (id NUMBER PRIMARY KEY, name VARCHAR2(50)); -- New table

-- === Indexes (5) ===
CREATE INDEX schema3.idx_emp_name ON schema3.emp (name);
CREATE INDEX schema4.idx_bonus_date ON schema4.bonus (bonus_date);
CREATE UNIQUE INDEX schema3.u_idx_mgr_email ON schema3.managers (email); -- New index
CREATE INDEX schema4.idx_prod_desc ON schema4.products (description); -- New index
CREATE INDEX schema4.idx_order_prod ON schema4.order_items (product_code); -- New index

-- === Sequences (4) ===
CREATE SEQUENCE schema3.emp_id_seq START WITH 1 INCREMENT BY 1; -- Different sequence
CREATE SEQUENCE schema4.bonus_seq START WITH 1000 INCREMENT BY 10; -- Different sequence
CREATE SEQUENCE schema4.supplier_seq START WITH 1; -- New sequence
CREATE SEQUENCE schema3.office_seq START WITH 1; -- New sequence

-- === Views (6) ===
CREATE OR REPLACE VIEW schema3.v_emp AS
SELECT id, name FROM schema3.emp; -- Updated view
CREATE OR REPLACE VIEW schema3.v_large_budget AS
SELECT dept_id, budget FROM schema3.dept WHERE budget > 100000; -- New view
CREATE OR REPLACE VIEW schema4.v_bonus AS
SELECT bonus_id, bonus_date FROM schema4.bonus; -- Updated view
CREATE OR REPLACE VIEW schema4.v_product_list AS
SELECT product_code, description FROM schema4.products ORDER BY product_code; -- New view
CREATE OR REPLACE VIEW schema3.v_managers AS
SELECT manager_id, email FROM schema3.managers; -- New view
CREATE OR REPLACE VIEW schema4.v_recent_log AS
SELECT action FROM schema4.audit_log WHERE log_id > 1000; -- New view

-- === Types (4) ===
CREATE OR REPLACE TYPE schema3.address_t AS OBJECT (
                                                       street VARCHAR2(100), -- Different size
                                                       city   VARCHAR2(100), -- Different size
                                                       zip    VARCHAR2(10)   -- Added element
                                                   );
/
CREATE OR REPLACE TYPE schema3.contact_info_t AS OBJECT ( -- New type
                                                            phone VARCHAR2(20),
                                                            fax   VARCHAR2(20)
                                                        );
/
CREATE OR REPLACE TYPE schema4.department_t AS OBJECT (
                                                          dept_name VARCHAR2(50),
                                                          manager   VARCHAR2(50) -- Added element
                                                      );
/
CREATE OR REPLACE TYPE schema4.order_t AS OBJECT ( -- New type
                                                     order_id NUMBER,
                                                     order_date DATE
                                                 );
/

-- === Procedures (4) ===
CREATE OR REPLACE PROCEDURE schema3.add_emp(p_id NUMBER, p_name VARCHAR2) AS -- Different signature
BEGIN
    INSERT INTO schema3.emp(id, name) VALUES (p_id, p_name);
END;
/
CREATE OR REPLACE PROCEDURE schema3.delete_office(p_office_id NUMBER) AS -- New procedure
BEGIN
    DELETE FROM schema3.offices WHERE office_id = p_office_id;
END;
/
CREATE OR REPLACE PROCEDURE schema4.add_bonus(p_bonus_id NUMBER) AS -- Different signature
BEGIN
    INSERT INTO schema4.bonus(bonus_id) VALUES (p_bonus_id);
END;
/
CREATE OR REPLACE PROCEDURE schema4.log_action(p_action VARCHAR2) AS -- New procedure
BEGIN
    INSERT INTO schema4.audit_log(action) VALUES (p_action);
END;
/

-- === Functions (4) ===
CREATE OR REPLACE FUNCTION schema3.check_manager_exists(p_id NUMBER) RETURN BOOLEAN AS -- New function
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM schema3.managers WHERE manager_id = p_id;
    RETURN v_count > 0;
END;
/
CREATE OR REPLACE FUNCTION schema3.get_office_location(p_id NUMBER) RETURN VARCHAR2 AS -- New function
BEGIN
    RETURN 'Unknown';
END;
/
CREATE OR REPLACE FUNCTION schema4.calculate_total_bonus(p_id NUMBER) RETURN NUMBER AS -- New function
BEGIN
    RETURN 500.00; -- Mock value
END;
/
CREATE OR REPLACE FUNCTION schema4.get_product_status(p_code VARCHAR2) RETURN VARCHAR2 AS -- New function
BEGIN
    RETURN 'AVAILABLE';
END;
/

-- === Packages (8 - 4 Specs, 4 Bodies) ===
CREATE OR REPLACE PACKAGE schema3.emp_pkg AS
    PROCEDURE log_emp(p_id NUMBER, p_name VARCHAR2); -- Different signature
    FUNCTION get_full_address(p_id NUMBER) RETURN schema3.address_t; -- New element
END emp_pkg;
/
CREATE OR REPLACE PACKAGE BODY schema3.emp_pkg AS
    PROCEDURE log_emp(p_id NUMBER, p_name VARCHAR2) IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Emp: ' || p_id || ' - ' || p_name);
    END;
    FUNCTION get_full_address(p_id NUMBER) RETURN schema3.address_t IS
    BEGIN
        RETURN schema3.address_t('123 Main St', 'Anytown', '12345');
    END;
END emp_pkg;
/
CREATE OR REPLACE PACKAGE schema4.salary_pkg AS
    PROCEDURE log_salary(p_id NUMBER, p_amount NUMBER); -- Different signature
    PROCEDURE grant_bonus(p_bonus_id NUMBER); -- New element
END salary_pkg;
/
CREATE OR REPLACE PACKAGE BODY schema4.salary_pkg AS
    PROCEDURE log_salary(p_id NUMBER, p_amount NUMBER) IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Salary ID: ' || p_id || ' Amount: ' || p_amount);
    END;
    PROCEDURE grant_bonus(p_bonus_id NUMBER) IS
    BEGIN
        NULL; -- Placeholder
    END;
END salary_pkg;
/

-- === Triggers (2) ===
CREATE OR REPLACE TRIGGER schema3.trg_backup_emp
    AFTER UPDATE OR DELETE ON schema3.emp
    FOR EACH ROW
BEGIN
    IF DELETING THEN
        INSERT INTO schema3.employees_backup (id, name) VALUES (:OLD.id, :OLD.name);
    END IF;
END;
/
CREATE OR REPLACE TRIGGER schema4.trg_log_new_supplier
    AFTER INSERT ON schema4.suppliers
    FOR EACH ROW
BEGIN
    schema4.log_action('NEW SUPPLIER: ' || :NEW.supplier_id);
END;
/


CREATE OR REPLACE PROCEDURE schema3.recreate_my_table(plan_name VARCHAR2) IS
BEGIN
    -- Try drop table, ignore any error
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE schema3.my_table_'||plan_name||' PURGE';
    EXCEPTION
        WHEN OTHERS THEN
            NULL; -- ignore drop errors
    END;

    -- Create table
    EXECUTE IMMEDIATE '
    CREATE TABLE schema3.my_table_' || plan_name|| ' (
                                      id        NUMBER PRIMARY KEY,
                                      name      VARCHAR2(100),
                                      created_at DATE DEFAULT SYSDATE
    )
    ';
END;
/
